version: '3.8'
services:
  app:
    image: openjdk:11
    container_name: app
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend:/srv:cached
    working_dir: /srv
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: mysql:8.0
    # コンテナ名を明示的に指定する
    container_name: ${DB_CONTAINER_NAME}
    # ホスト名を明示的に指定する
    hostname: ${DB_HOST_NAME}
    ports:
      - ${LOCAL_DB_PORT_NO}:${INNER_DB_PORT_NO}
    volumes:
      # 作成した volume に /var/lib/mysql をマウント
      - ./docker/db/store:/var/lib/mysql
      - ./docker/db/logs:/var/log/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PWD}
      - TZ=${TZ}
